package com.link.up.connector.jdbc.catalog.yashandb;

import com.link.up.api.table.catalog.CatalogTable;
import com.link.up.api.table.catalog.Column;
import com.link.up.api.table.catalog.PrimaryKey;
import com.link.up.api.table.catalog.TablePath;
import com.link.up.api.table.catalog.TableSchema;
import com.link.up.api.table.type.SqlType;
import com.link.up.connector.jdbc.core.dialect.yashandb.YashanDbTypeMapper;

import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import java.util.regex.Pattern;
import java.util.stream.Collectors;

/** YashanDB offline CREATE TABLE builder. */
public final class YashanDbCreateTableSqlBuilder {

    private static final Pattern NUMBER_PATTERN =
            Pattern.compile("[-+]?\\d+(\\.\\d+)?");

    private final TablePath tablePath;
    private final CatalogTable catalogTable;
    private final YashanDbTypeMapper typeMapper;

    public YashanDbCreateTableSqlBuilder(
            TablePath tablePath,
            CatalogTable catalogTable,
            YashanDbTypeMapper typeMapper) {
        this.tablePath = tablePath;
        this.catalogTable = catalogTable;
        this.typeMapper = typeMapper;
    }

    public String build() {
        return buildStatements().stream()
                .map(sql -> sql.endsWith(";") ? sql : sql + ";")
                .collect(Collectors.joining("\n"));
    }

    public List<String> buildStatements() {
        TableSchema schema = catalogTable.getTableSchema();
        boolean preserveSourceType =
                YashanDbCatalog.DIALECT.equalsIgnoreCase(
                        catalogTable.getOptions().get(
                                YashanDbCatalog.TABLE_OPTION_DIALECT));

        List<String> definitions = new ArrayList<String>();
        for (Column column : schema.getColumns()) {
            definitions.add(buildColumnDefinition(column, preserveSourceType));
        }

        PrimaryKey primaryKey = schema.getPrimaryKey();
        if (primaryKey != null) {
            definitions.add(buildPrimaryKey(primaryKey));
        }

        List<String> statements = new ArrayList<String>();
        statements.add(
                "CREATE TABLE " + quoteTable(tablePath)
                        + " (\n    "
                        + String.join(",\n    ", definitions)
                        + "\n)");

        if (hasText(catalogTable.getComment())) {
            statements.add(
                    "COMMENT ON TABLE " + quoteTable(tablePath)
                            + " IS '" + escapeLiteral(catalogTable.getComment()) + "'");
        }

        for (Column column : schema.getColumns()) {
            if (hasText(column.getComment())) {
                statements.add(
                        "COMMENT ON COLUMN " + quoteTable(tablePath) + "."
                                + quoteIdentifier(column.getName())
                                + " IS '" + escapeLiteral(column.getComment()) + "'");
            }
        }
        return statements;
    }

    public String buildColumnDefinition(
            Column column,
            boolean preserveSourceType) {

        List<String> parts = new ArrayList<String>();
        parts.add(quoteIdentifier(column.getName()));
        parts.add(typeMapper.toDatabaseType(column, preserveSourceType));

        if (column.isAutoIncrement()) {
            if (!isInteger(column.getDataType().getSqlType())) {
                throw new IllegalArgumentException(
                        "YashanDB identity column must be integer, column="
                                + column.getName());
            }
            parts.add("GENERATED BY DEFAULT AS IDENTITY");
        } else if (column.getDefaultValue() != null) {
            parts.add("DEFAULT " + formatDefaultValue(column, preserveSourceType));
        }

        if (!column.isNullable()) {
            parts.add("NOT NULL");
        }
        return String.join(" ", parts);
    }

    private String buildPrimaryKey(PrimaryKey primaryKey) {
        String constraintName = primaryKey.getName();
        if (!hasText(constraintName)) {
            constraintName = "PK_" + tablePath.getTableName();
        }
        constraintName = normalizeConstraintName(constraintName);

        String columns = primaryKey.getColumnNames().stream()
                .map(YashanDbCreateTableSqlBuilder::quoteIdentifier)
                .collect(Collectors.joining(", "));
        return "CONSTRAINT " + quoteIdentifier(constraintName)
                + " PRIMARY KEY (" + columns + ")";
    }

    private String formatDefaultValue(
            Column column,
            boolean preserveSourceType) {

        Object value = column.getDefaultValue();
        String text = String.valueOf(value).trim();

        if (preserveSourceType && hasText(text)) {
            return text;
        }
        if (value instanceof Number) {
            return value.toString();
        }
        if (value instanceof Boolean) {
            return (Boolean) value ? "TRUE" : "FALSE";
        }

        String upper = text.toUpperCase(Locale.ROOT);
        if ("NULL".equals(upper)
                || "CURRENT_DATE".equals(upper)
                || upper.startsWith("CURRENT_TIMESTAMP")
                || "SYSDATE".equals(upper)
                || "SYSTIMESTAMP".equals(upper)
                || "CURRENT_USER".equals(upper)
                || "SESSION_USER".equals(upper)
                || upper.endsWith(".NEXTVAL")) {
            return text;
        }

        if (isNumeric(column.getDataType().getSqlType())
                && NUMBER_PATTERN.matcher(text).matches()) {
            return text;
        }
        return "'" + escapeLiteral(text) + "'";
    }

    private static boolean isInteger(SqlType type) {
        return type == SqlType.TINYINT
                || type == SqlType.SMALLINT
                || type == SqlType.INT
                || type == SqlType.BIGINT;
    }

    private static boolean isNumeric(SqlType type) {
        return isInteger(type)
                || type == SqlType.FLOAT
                || type == SqlType.DOUBLE
                || type == SqlType.DECIMAL;
    }

    private static String normalizeConstraintName(String value) {
        String normalized = value.trim().replaceAll("[^A-Za-z0-9_$#]", "_");
        return normalized.length() > 64 ? normalized.substring(0, 64) : normalized;
    }

    private static String quoteTable(TablePath path) {
        if (!hasText(path.getSchemaName())) {
            throw new IllegalArgumentException(
                    "YashanDB CREATE TABLE 需要 schema：" + path);
        }
        return quoteIdentifier(path.getSchemaName())
                + "."
                + quoteIdentifier(path.getTableName());
    }

    private static String quoteIdentifier(String value) {
        if (!hasText(value)) {
            throw new IllegalArgumentException("identifier must not be empty");
        }
        return "\"" + value.trim().replace("\"", "\"\"") + "\"";
    }

    private static String escapeLiteral(String value) {
        return value.replace("'", "''");
    }

    private static boolean hasText(String value) {
        return value != null && !value.trim().isEmpty();
    }
}
