package com.link.up.connector.jdbc.catalog.kingbase;

import com.link.up.api.table.catalog.CatalogTable;
import com.link.up.api.table.catalog.Column;
import com.link.up.api.table.catalog.PrimaryKey;
import com.link.up.api.table.catalog.TablePath;
import com.link.up.api.table.catalog.TableSchema;
import com.link.up.api.table.type.SqlType;
import com.link.up.connector.jdbc.core.dialect.kingbase.KingbaseTypeMapper;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Locale;
import java.util.regex.Pattern;
import java.util.stream.Collectors;

/** KingbaseES offline CREATE TABLE builder. */
public final class KingbaseCreateTableSqlBuilder {

    private static final Pattern NUMBER_PATTERN =
            Pattern.compile("[-+]?\\d+(\\.\\d+)?");

    private final TablePath tablePath;
    private final CatalogTable catalogTable;
    private final KingbaseTypeMapper typeMapper;

    public KingbaseCreateTableSqlBuilder(
            TablePath tablePath,
            CatalogTable catalogTable,
            KingbaseTypeMapper typeMapper) {
        this.tablePath = tablePath;
        this.catalogTable = catalogTable;
        this.typeMapper = typeMapper;
    }

    public String build() {
        return String.join("\n", buildStatements());
    }

    public List<String> buildStatements() {
        List<String> statements = new ArrayList<String>();
        statements.add(buildCreateTable());

        if (hasText(catalogTable.getComment())) {
            statements.add(
                    "COMMENT ON TABLE " + quoteTable(tablePath)
                            + " IS '" + escapeLiteral(catalogTable.getComment()) + "';");
        }
        for (Column column : catalogTable.getTableSchema().getColumns()) {
            if (hasText(column.getComment())) {
                statements.add(
                        "COMMENT ON COLUMN " + quoteTable(tablePath) + "."
                                + quoteIdentifier(column.getName())
                                + " IS '" + escapeLiteral(column.getComment()) + "';");
            }
        }
        return Collections.unmodifiableList(statements);
    }

    public String buildColumnDefinition(
            Column column,
            boolean preserveSourceType) {

        List<String> parts = new ArrayList<String>();
        parts.add(quoteIdentifier(column.getName()));
        parts.add(typeMapper.toDatabaseType(column, preserveSourceType));

        if (column.isAutoIncrement()
                && isInteger(column.getDataType().getSqlType())) {
            parts.add("GENERATED BY DEFAULT AS IDENTITY");
        }

        parts.add(column.isNullable() ? "NULL" : "NOT NULL");

        if (!column.isAutoIncrement() && column.getDefaultValue() != null) {
            parts.add("DEFAULT " + formatDefaultValue(column, preserveSourceType));
        }
        return String.join(" ", parts);
    }

    private String buildCreateTable() {
        TableSchema schema = catalogTable.getTableSchema();
        boolean preserveSourceType = KingbaseCatalog.DIALECT.equalsIgnoreCase(
                catalogTable.getOptions().get(KingbaseCatalog.TABLE_OPTION_DIALECT));

        List<String> definitions = new ArrayList<String>();
        for (Column column : schema.getColumns()) {
            definitions.add(buildColumnDefinition(column, preserveSourceType));
        }

        PrimaryKey primaryKey = schema.getPrimaryKey();
        if (primaryKey != null) {
            definitions.add(buildPrimaryKey(primaryKey));
        }

        StringBuilder sql = new StringBuilder()
                .append("CREATE TABLE ")
                .append(quoteTable(tablePath))
                .append(" (\n    ")
                .append(String.join(",\n    ", definitions))
                .append("\n)");

        String fillfactor = catalogTable.getOptions().get(
                KingbaseCatalog.TABLE_OPTION_FILLFACTOR);
        if (hasText(fillfactor)) {
            sql.append("\nWITH (fillfactor=")
                    .append(normalizeFillfactor(fillfactor))
                    .append(")");
        }

        String tablespace = catalogTable.getOptions().get(
                KingbaseCatalog.TABLE_OPTION_TABLESPACE);
        if (hasText(tablespace)) {
            sql.append("\nTABLESPACE ")
                    .append(quoteIdentifier(normalizeTablespace(tablespace)));
        }
        sql.append(';');
        return sql.toString();
    }

    private static String buildPrimaryKey(PrimaryKey primaryKey) {
        String columns = primaryKey.getColumnNames().stream()
                .map(KingbaseCreateTableSqlBuilder::quoteIdentifier)
                .collect(Collectors.joining(", "));
        if (!hasText(primaryKey.getName())) {
            return "PRIMARY KEY (" + columns + ")";
        }
        return "CONSTRAINT " + quoteIdentifier(primaryKey.getName())
                + " PRIMARY KEY (" + columns + ")";
    }

    private static String formatDefaultValue(
            Column column,
            boolean preserveSourceType) {

        Object value = column.getDefaultValue();
        if (value instanceof Number) {
            return value.toString();
        }
        if (value instanceof Boolean) {
            return (Boolean) value ? "TRUE" : "FALSE";
        }

        String text = String.valueOf(value).trim();
        if (preserveSourceType) {
            return text;
        }

        String upper = text.toUpperCase(Locale.ROOT);
        if ("NULL".equals(upper)
                || "CURRENT_TIMESTAMP".equals(upper)
                || upper.startsWith("CURRENT_TIMESTAMP(")
                || "CURRENT_DATE".equals(upper)
                || "CURRENT_TIME".equals(upper)
                || "NOW()".equals(upper)
                || "SYSDATE".equals(upper)
                || "CURRENT_USER".equals(upper)
                || "SESSION_USER".equals(upper)
                || "USER".equals(upper)) {
            return text;
        }

        SqlType sqlType = column.getDataType().getSqlType();
        if (isNumeric(sqlType) && NUMBER_PATTERN.matcher(text).matches()) {
            return text;
        }
        return "'" + escapeLiteral(text) + "'";
    }

    static String normalizeFillfactor(String value) {
        String normalized = value.trim();
        int fillfactor;
        try {
            fillfactor = Integer.parseInt(normalized);
        } catch (NumberFormatException e) {
            throw new IllegalArgumentException(
                    "KingbaseES fillfactor 必须是 10..100 的整数：" + value, e);
        }
        if (fillfactor < 10 || fillfactor > 100) {
            throw new IllegalArgumentException(
                    "KingbaseES fillfactor 必须在 10..100：" + value);
        }
        return String.valueOf(fillfactor);
    }

    static String normalizeTablespace(String value) {
        String normalized = value.trim();
        if (!hasText(normalized)
                || normalized.indexOf('\"') >= 0
                || normalized.indexOf('\n') >= 0
                || normalized.indexOf('\r') >= 0
                || normalized.indexOf(';') >= 0) {
            throw new IllegalArgumentException(
                    "KingbaseES tablespace 包含非法字符：" + value);
        }
        return normalized;
    }

    private static boolean isInteger(SqlType type) {
        return type == SqlType.TINYINT
                || type == SqlType.SMALLINT
                || type == SqlType.INT
                || type == SqlType.BIGINT;
    }

    private static boolean isNumeric(SqlType type) {
        return isInteger(type)
                || type == SqlType.FLOAT
                || type == SqlType.DOUBLE
                || type == SqlType.DECIMAL;
    }

    private static String quoteTable(TablePath path) {
        if (!hasText(path.getSchemaName())) {
            throw new IllegalArgumentException(
                    "KingbaseES CREATE TABLE 需要 schema：" + path);
        }
        return quoteIdentifier(path.getSchemaName())
                + "."
                + quoteIdentifier(path.getTableName());
    }

    private static String quoteIdentifier(String value) {
        if (!hasText(value)) {
            throw new IllegalArgumentException("identifier must not be empty");
        }
        return "\"" + value.trim().replace("\"", "\"\"") + "\"";
    }

    private static String escapeLiteral(String value) {
        return value.replace("'", "''");
    }

    private static boolean hasText(String value) {
        return value != null && !value.trim().isEmpty();
    }
}
