package com.link.up.connector.jdbc.catalog.opengauss;

import com.link.up.api.table.catalog.CatalogTable;
import com.link.up.api.table.catalog.Column;
import com.link.up.api.table.catalog.PrimaryKey;
import com.link.up.api.table.catalog.TablePath;
import com.link.up.api.table.catalog.TableSchema;
import com.link.up.api.table.type.SqlType;
import com.link.up.connector.jdbc.core.dialect.opengauss.OpenGaussTypeMapper;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Locale;
import java.util.regex.Pattern;
import java.util.stream.Collectors;

/** openGauss offline CREATE TABLE builder. */
public final class OpenGaussCreateTableSqlBuilder {

    private static final Pattern NUMBER_PATTERN =
            Pattern.compile("[-+]?\\d+(\\.\\d+)?");

    private final TablePath tablePath;
    private final CatalogTable catalogTable;
    private final OpenGaussTypeMapper typeMapper;

    public OpenGaussCreateTableSqlBuilder(
            TablePath tablePath,
            CatalogTable catalogTable,
            OpenGaussTypeMapper typeMapper) {

        this.tablePath = tablePath;
        this.catalogTable = catalogTable;
        this.typeMapper = typeMapper;
    }

    public String build() {
        return String.join("\n", buildStatements());
    }

    public List<String> buildStatements() {
        List<String> statements = new ArrayList<String>();
        statements.add(buildCreateTable());

        if (hasText(catalogTable.getComment())) {
            statements.add(
                    "COMMENT ON TABLE " + quoteTable(tablePath)
                            + " IS '" + escapeLiteral(catalogTable.getComment()) + "';");
        }

        for (Column column : catalogTable.getTableSchema().getColumns()) {
            if (hasText(column.getComment())) {
                statements.add(
                        "COMMENT ON COLUMN " + quoteTable(tablePath) + "."
                                + quoteIdentifier(column.getName())
                                + " IS '" + escapeLiteral(column.getComment()) + "';");
            }
        }
        return Collections.unmodifiableList(statements);
    }

    public String buildColumnDefinition(
            Column column,
            boolean preserveSourceType) {

        List<String> parts = new ArrayList<String>();
        parts.add(quoteIdentifier(column.getName()));
        parts.add(typeMapper.toDatabaseType(column, preserveSourceType));

        if (column.isAutoIncrement()
                && isInteger(column.getDataType().getSqlType())) {
            parts.add("GENERATED BY DEFAULT AS IDENTITY");
        }

        parts.add(column.isNullable() ? "NULL" : "NOT NULL");

        if (!column.isAutoIncrement() && column.getDefaultValue() != null) {
            parts.add("DEFAULT " + formatDefaultValue(column, preserveSourceType));
        }

        return String.join(" ", parts);
    }

    private String buildCreateTable() {
        TableSchema schema = catalogTable.getTableSchema();
        List<String> definitions = new ArrayList<String>();

        boolean preserveSourceType =
                OpenGaussCatalog.DIALECT.equalsIgnoreCase(
                        catalogTable.getOptions().get(
                                OpenGaussCatalog.TABLE_OPTION_DIALECT));

        for (Column column : schema.getColumns()) {
            definitions.add(buildColumnDefinition(column, preserveSourceType));
        }

        PrimaryKey primaryKey = schema.getPrimaryKey();
        if (primaryKey != null) {
            definitions.add(buildPrimaryKey(primaryKey));
        }

        return "CREATE TABLE " + quoteTable(tablePath)
                + " (\n    "
                + String.join(",\n    ", definitions)
                + "\n);";
    }

    private static String buildPrimaryKey(PrimaryKey primaryKey) {
        String columns = primaryKey.getColumnNames().stream()
                .map(OpenGaussCreateTableSqlBuilder::quoteIdentifier)
                .collect(Collectors.joining(", "));
        return "PRIMARY KEY (" + columns + ")";
    }

    private static String formatDefaultValue(
            Column column,
            boolean preserveSourceType) {

        Object value = column.getDefaultValue();
        if (value instanceof Number) {
            return value.toString();
        }
        if (value instanceof Boolean) {
            return (Boolean) value ? "TRUE" : "FALSE";
        }

        String text = String.valueOf(value).trim();
        if (preserveSourceType) {
            return text;
        }

        String upper = text.toUpperCase(Locale.ROOT);
        if ("NULL".equals(upper)
                || "CURRENT_TIMESTAMP".equals(upper)
                || upper.startsWith("CURRENT_TIMESTAMP(")
                || "CURRENT_DATE".equals(upper)
                || "CURRENT_TIME".equals(upper)
                || "NOW()".equals(upper)
                || "SYSDATE".equals(upper)
                || "CURRENT_USER".equals(upper)
                || "SESSION_USER".equals(upper)) {
            return text;
        }

        SqlType sqlType = column.getDataType().getSqlType();
        if (isNumeric(sqlType) && NUMBER_PATTERN.matcher(text).matches()) {
            return text;
        }
        return "'" + escapeLiteral(text) + "'";
    }

    private static boolean isInteger(SqlType type) {
        return type == SqlType.TINYINT
                || type == SqlType.SMALLINT
                || type == SqlType.INT
                || type == SqlType.BIGINT;
    }

    private static boolean isNumeric(SqlType type) {
        return isInteger(type)
                || type == SqlType.FLOAT
                || type == SqlType.DOUBLE
                || type == SqlType.DECIMAL;
    }

    private static String quoteTable(TablePath path) {
        if (!hasText(path.getSchemaName())) {
            throw new IllegalArgumentException(
                    "openGauss CREATE TABLE 需要 schema：" + path);
        }
        return quoteIdentifier(path.getSchemaName())
                + "."
                + quoteIdentifier(path.getTableName());
    }

    private static String quoteIdentifier(String value) {
        if (!hasText(value)) {
            throw new IllegalArgumentException("identifier must not be empty");
        }
        return "\"" + value.trim().replace("\"", "\"\"") + "\"";
    }

    private static String escapeLiteral(String value) {
        return value.replace("'", "''");
    }

    private static boolean hasText(String value) {
        return value != null && !value.trim().isEmpty();
    }
}
