package com.link.up.connector.jdbc.catalog.highgo;

import com.link.up.api.table.catalog.CatalogTable;
import com.link.up.api.table.catalog.Column;
import com.link.up.api.table.catalog.PrimaryKey;
import com.link.up.api.table.catalog.TablePath;
import com.link.up.api.table.catalog.TableSchema;
import com.link.up.api.table.type.SqlType;
import com.link.up.connector.jdbc.core.dialect.highgo.HighGoTypeMapper;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Locale;
import java.util.regex.Pattern;
import java.util.stream.Collectors;

/** HighGo CREATE TABLE builder for offline Sink preparation. */
public final class HighGoCreateTableSqlBuilder {

    private static final Pattern NUMBER_PATTERN =
            Pattern.compile("[-+]?\\d+(\\.\\d+)?([eE][-+]?\\d+)?");

    private final TablePath tablePath;
    private final CatalogTable catalogTable;
    private final HighGoTypeMapper typeMapper;

    public HighGoCreateTableSqlBuilder(
            TablePath tablePath,
            CatalogTable catalogTable,
            HighGoTypeMapper typeMapper) {
        this.tablePath = tablePath;
        this.catalogTable = catalogTable;
        this.typeMapper = typeMapper;
    }

    public String build() {
        return String.join("\n", buildStatements());
    }

    public List<String> buildStatements() {
        List<String> statements = new ArrayList<String>();
        statements.add(buildCreateTable());

        if (hasText(catalogTable.getComment())) {
            statements.add(
                    "COMMENT ON TABLE " + quoteTable(tablePath)
                            + " IS '" + escapeLiteral(catalogTable.getComment()) + "';");
        }

        for (Column column : catalogTable.getTableSchema().getColumns()) {
            if (hasText(column.getComment())) {
                statements.add(
                        "COMMENT ON COLUMN " + quoteTable(tablePath) + "."
                                + quoteIdentifier(column.getName())
                                + " IS '" + escapeLiteral(column.getComment()) + "';");
            }
        }
        return Collections.unmodifiableList(statements);
    }

    public String buildColumnDefinition(
            Column column,
            boolean preserveSourceType) {

        List<String> parts = new ArrayList<String>();
        parts.add(quoteIdentifier(column.getName()));
        parts.add(typeMapper.toDatabaseType(column, preserveSourceType));

        if (column.isAutoIncrement()) {
            if (!isInteger(column.getDataType().getSqlType())) {
                throw new IllegalArgumentException(
                        "HighGo identity 仅为整数 Flux 类型生成，column="
                                + column.getName() + "，type="
                                + column.getDataType().getSqlType());
            }
            parts.add("GENERATED BY DEFAULT AS IDENTITY");
        }

        parts.add(column.isNullable() ? "NULL" : "NOT NULL");

        if (!column.isAutoIncrement() && column.getDefaultValue() != null) {
            parts.add("DEFAULT " + formatDefaultValue(column, preserveSourceType));
        }

        return String.join(" ", parts);
    }

    private String buildCreateTable() {
        TableSchema schema = catalogTable.getTableSchema();
        boolean preserveSourceType = HighGoCatalog.DIALECT.equalsIgnoreCase(
                catalogTable.getOptions().get(HighGoCatalog.TABLE_OPTION_DIALECT));

        List<String> definitions = new ArrayList<String>();
        for (Column column : schema.getColumns()) {
            definitions.add(buildColumnDefinition(column, preserveSourceType));
        }

        PrimaryKey primaryKey = schema.getPrimaryKey();
        if (primaryKey != null) {
            definitions.add(buildPrimaryKey(primaryKey));
        }

        return "CREATE TABLE " + quoteTable(tablePath)
                + " (\n    " + String.join(",\n    ", definitions) + "\n);";
    }

    private String buildPrimaryKey(PrimaryKey primaryKey) {
        String columns = primaryKey.getColumnNames().stream()
                .map(HighGoCreateTableSqlBuilder::quoteIdentifier)
                .collect(Collectors.joining(", "));
        if (hasText(primaryKey.getName())) {
            return "CONSTRAINT " + quoteIdentifier(normalizeConstraintName(primaryKey.getName()))
                    + " PRIMARY KEY (" + columns + ")";
        }
        return "PRIMARY KEY (" + columns + ")";
    }

    private String formatDefaultValue(Column column, boolean preserveSourceType) {
        Object value = column.getDefaultValue();
        if (preserveSourceType) {
            String expression = String.valueOf(value).trim();
            if (hasText(expression)) {
                return expression;
            }
        }
        if (value instanceof Number) {
            return value.toString();
        }
        if (value instanceof Boolean) {
            return (Boolean) value ? "TRUE" : "FALSE";
        }

        String text = String.valueOf(value).trim();
        String upper = text.toUpperCase(Locale.ROOT);
        if ("NULL".equals(upper)
                || "CURRENT_TIMESTAMP".equals(upper)
                || upper.startsWith("CURRENT_TIMESTAMP(")
                || "CURRENT_DATE".equals(upper)
                || "CURRENT_TIME".equals(upper)
                || upper.startsWith("CURRENT_TIME(")
                || "LOCALTIMESTAMP".equals(upper)
                || upper.startsWith("LOCALTIMESTAMP(")
                || "LOCALTIME".equals(upper)
                || upper.startsWith("LOCALTIME(")
                || "NOW()".equals(upper)
                || upper.endsWith(".NEXTVAL")) {
            return text;
        }

        if (isNumeric(column.getDataType().getSqlType())
                && NUMBER_PATTERN.matcher(text).matches()) {
            return text;
        }

        return "'" + escapeLiteral(text) + "'";
    }

    private static boolean isInteger(SqlType type) {
        return type == SqlType.TINYINT
                || type == SqlType.SMALLINT
                || type == SqlType.INT
                || type == SqlType.BIGINT;
    }

    private static boolean isNumeric(SqlType type) {
        return isInteger(type)
                || type == SqlType.FLOAT
                || type == SqlType.DOUBLE
                || type == SqlType.DECIMAL;
    }

    private static String normalizeConstraintName(String value) {
        String normalized = value.trim().replaceAll("[^A-Za-z0-9_$#]", "_");
        return normalized.length() > 63 ? normalized.substring(0, 63) : normalized;
    }

    private static String quoteTable(TablePath path) {
        if (!hasText(path.getSchemaName())) {
            throw new IllegalArgumentException(
                    "HighGo tablePath must contain schema: " + path);
        }
        return quoteIdentifier(path.getSchemaName())
                + "." + quoteIdentifier(path.getTableName());
    }

    private static String quoteIdentifier(String value) {
        if (!hasText(value)) {
            throw new IllegalArgumentException("identifier must not be empty");
        }
        return "\"" + value.trim().replace("\"", "\"\"") + "\"";
    }

    private static String escapeLiteral(String value) {
        return value.replace("'", "''");
    }

    private static boolean hasText(String value) {
        return value != null && !value.trim().isEmpty();
    }
}
