package com.link.up.connector.jdbc.catalog.highgo;

import com.link.up.api.table.catalog.CatalogTable;
import com.link.up.api.table.catalog.Column;
import com.link.up.api.table.catalog.PrimaryKey;
import com.link.up.api.table.catalog.TablePath;
import com.link.up.api.table.catalog.TableSchema;
import com.link.up.api.table.type.BasicType;
import com.link.up.api.table.type.DecimalType;
import com.link.up.connector.jdbc.core.dialect.highgo.HighGoTypeMapper;
import org.junit.Test;

import java.util.Arrays;

import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertTrue;

public class HighGoCreateTableSqlBuilderTest {

    @Test
    public void buildsCreateTableWithIdentityPrimaryKeyAndComments() {
        TablePath path = TablePath.of("highgo", "app", "users");
        TableSchema schema = TableSchema.builder()
                .column(Column.builder("id", BasicType.LONG_TYPE)
                        .nullable(false)
                        .autoIncrement(true)
                        .build())
                .column(Column.builder("name", BasicType.STRING_TYPE)
                        .length(64L)
                        .comment("display name")
                        .build())
                .column(Column.builder("amount", new DecimalType(1000, 20)).build())
                .primaryKey(PrimaryKey.of("pk_users", Arrays.asList("id")))
                .build();
        CatalogTable table = CatalogTable.builder(path, schema)
                .comment("users table")
                .build();

        String ddl = new HighGoCreateTableSqlBuilder(
                path,
                table,
                new HighGoTypeMapper())
                .build();

        assertTrue(ddl.contains("CREATE TABLE \"app\".\"users\""));
        assertTrue(ddl.contains(
                "\"id\" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL"));
        assertTrue(ddl.contains("\"name\" VARCHAR(64) NULL"));
        assertTrue(ddl.contains("\"amount\" NUMERIC(1000,20) NULL"));
        assertTrue(ddl.contains(
                "CONSTRAINT \"pk_users\" PRIMARY KEY (\"id\")"));
        assertTrue(ddl.contains(
                "COMMENT ON TABLE \"app\".\"users\" IS 'users table'"));
        assertTrue(ddl.contains(
                "COMMENT ON COLUMN \"app\".\"users\".\"name\" IS 'display name'"));
    }

    @Test
    public void sameDialectPreservesCoreTypesButNormalizesCompatibilityAliases() {
        TablePath path = TablePath.of("highgo", "app", "events");
        TableSchema schema = TableSchema.builder()
                .column(Column.builder("payload", BasicType.STRING_TYPE)
                        .sourceType("JSONB")
                        .build())
                .column(Column.builder("legacy_text", BasicType.STRING_TYPE)
                        .sourceType("CLOB")
                        .build())
                .build();
        CatalogTable table = CatalogTable.builder(path, schema)
                .option(HighGoCatalog.TABLE_OPTION_DIALECT, HighGoCatalog.DIALECT)
                .build();

        String ddl = new HighGoCreateTableSqlBuilder(
                path,
                table,
                new HighGoTypeMapper())
                .build();

        assertTrue(ddl.contains("\"payload\" JSONB NULL"));
        assertTrue(ddl.contains("\"legacy_text\" TEXT NULL"));
        assertFalse(ddl.contains("\"legacy_text\" CLOB"));
    }

    @Test(expected = IllegalArgumentException.class)
    public void rejectsAutoIncrementForNonIntegerFluxType() {
        TablePath path = TablePath.of("highgo", "app", "events");
        TableSchema schema = TableSchema.builder()
                .column(Column.builder("id", new DecimalType(20, 0))
                        .autoIncrement(true)
                        .build())
                .build();
        CatalogTable table = CatalogTable.builder(path, schema).build();

        new HighGoCreateTableSqlBuilder(
                path,
                table,
                new HighGoTypeMapper())
                .build();
    }
}
