package com.link.up.connector.jdbc.catalog.kingbase;

import com.link.up.api.table.catalog.CatalogTable;
import com.link.up.api.table.catalog.Column;
import com.link.up.api.table.catalog.PrimaryKey;
import com.link.up.api.table.catalog.TablePath;
import com.link.up.api.table.catalog.TableSchema;
import com.link.up.api.table.type.BasicType;
import com.link.up.api.table.type.DecimalType;
import com.link.up.connector.jdbc.core.dialect.kingbase.KingbaseTypeMapper;
import org.junit.Test;

import java.util.Arrays;

import static org.junit.Assert.assertTrue;

public class KingbaseCreateTableSqlBuilderTest {

    @Test
    public void buildsCreateTableWithIdentityStoragePrimaryKeyAndComments() {
        TablePath path = TablePath.of("TEST", "app", "users");
        TableSchema schema = TableSchema.builder()
                .column(Column.builder("id", BasicType.LONG_TYPE)
                        .nullable(false)
                        .autoIncrement(true)
                        .build())
                .column(Column.builder("name", BasicType.STRING_TYPE)
                        .length(64L)
                        .comment("display name")
                        .build())
                .column(Column.builder("amount", new DecimalType(1000, 20)).build())
                .primaryKey(PrimaryKey.of("pk_users", Arrays.asList("id")))
                .build();
        CatalogTable table = CatalogTable.builder(path, schema)
                .comment("users table")
                .option(KingbaseCatalog.TABLE_OPTION_FILLFACTOR, "90")
                .option(KingbaseCatalog.TABLE_OPTION_TABLESPACE, "DATA_TS")
                .build();

        String ddl = new KingbaseCreateTableSqlBuilder(
                path,
                table,
                new KingbaseTypeMapper())
                .build();

        assertTrue(ddl.contains("CREATE TABLE \"app\".\"users\""));
        assertTrue(ddl.contains(
                "\"id\" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL"));
        assertTrue(ddl.contains("\"name\" VARCHAR(64) NULL"));
        assertTrue(ddl.contains("\"amount\" NUMERIC(1000,20) NULL"));
        assertTrue(ddl.contains(
                "CONSTRAINT \"pk_users\" PRIMARY KEY (\"id\")"));
        assertTrue(ddl.contains("WITH (fillfactor=90)"));
        assertTrue(ddl.contains("TABLESPACE \"DATA_TS\""));
        assertTrue(ddl.contains(
                "COMMENT ON TABLE \"app\".\"users\" IS 'users table'"));
        assertTrue(ddl.contains(
                "COMMENT ON COLUMN \"app\".\"users\".\"name\" IS 'display name'"));
    }

    @Test
    public void preservesNativeTypeForSameDialectDdl() {
        TablePath path = TablePath.of("TEST", "app", "events");
        TableSchema schema = TableSchema.builder()
                .column(Column.builder("flags", BasicType.STRING_TYPE)
                        .sourceType("BIT(8)")
                        .build())
                .column(Column.builder("payload", BasicType.STRING_TYPE)
                        .sourceType("JSONB")
                        .build())
                .build();
        CatalogTable table = CatalogTable.builder(path, schema)
                .option(KingbaseCatalog.TABLE_OPTION_DIALECT, KingbaseCatalog.DIALECT)
                .build();

        String ddl = new KingbaseCreateTableSqlBuilder(
                path,
                table,
                new KingbaseTypeMapper())
                .build();

        assertTrue(ddl.contains("\"flags\" BIT(8) NULL"));
        assertTrue(ddl.contains("\"payload\" JSONB NULL"));
    }

    @Test(expected = IllegalArgumentException.class)
    public void rejectsUnsafeFillfactor() {
        TablePath path = TablePath.of("TEST", "app", "events");
        CatalogTable table = CatalogTable.builder(
                        path,
                        TableSchema.builder()
                                .column(Column.builder("id", BasicType.INT_TYPE).build())
                                .build())
                .option(KingbaseCatalog.TABLE_OPTION_FILLFACTOR, "101")
                .build();
        new KingbaseCreateTableSqlBuilder(path, table, new KingbaseTypeMapper()).build();
    }
}
