package com.link.up.connector.jdbc.catalog.duckdb;

import com.link.up.api.table.catalog.CatalogTable;
import com.link.up.api.table.catalog.Column;
import com.link.up.api.table.catalog.PrimaryKey;
import com.link.up.api.table.catalog.TablePath;
import com.link.up.api.table.catalog.TableSchema;
import com.link.up.api.table.type.BasicType;
import com.link.up.api.table.type.DecimalType;
import com.link.up.connector.jdbc.core.dialect.duckdb.DuckDbTypeMapper;
import org.junit.Test;

import java.util.Arrays;

import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertTrue;

public class DuckDbCreateTableSqlBuilderTest {

    @Test
    public void buildsSequenceBackedIdentityPrimaryKeyAndComments() {
        TablePath path = TablePath.of("warehouse", "main", "users");
        TableSchema schema = TableSchema.builder()
                .column(Column.builder("id", BasicType.LONG_TYPE)
                        .nullable(false)
                        .autoIncrement(true)
                        .build())
                .column(Column.builder("name", BasicType.STRING_TYPE)
                        .nullable(false)
                        .comment("display name")
                        .build())
                .column(Column.builder("amount", new DecimalType(38, 12))
                        .build())
                .primaryKey(PrimaryKey.of("pk_users", Arrays.asList("id")))
                .build();
        CatalogTable table = CatalogTable.builder(path, schema)
                .comment("users table")
                .build();

        String ddl = new DuckDbCreateTableSqlBuilder(
                path,
                table,
                new DuckDbTypeMapper())
                .build();

        assertTrue(ddl.contains(
                "CREATE SEQUENCE IF NOT EXISTS \"main\".\"users_id_seq\""));
        assertTrue(ddl.contains("CREATE TABLE \"main\".\"users\""));
        assertTrue(ddl.contains(
                "\"id\" BIGINT DEFAULT nextval('\"main\".\"users_id_seq\"') NOT NULL"));
        assertFalse(ddl.contains("GENERATED BY DEFAULT AS IDENTITY"));
        assertTrue(ddl.contains("\"name\" VARCHAR NOT NULL"));
        assertTrue(ddl.contains("\"amount\" DECIMAL(38,12)"));
        assertTrue(ddl.contains(
                "CONSTRAINT \"pk_users\" PRIMARY KEY (\"id\")"));
        assertTrue(ddl.contains(
                "COMMENT ON TABLE \"main\".\"users\" IS 'users table'"));
        assertTrue(ddl.contains(
                "COMMENT ON COLUMN \"main\".\"users\".\"name\" IS 'display name'"));
    }

    @Test
    public void preservesSafeNativeScalarTypeForSameDialectDdl() {
        TablePath path = TablePath.of("warehouse", "main", "events");
        TableSchema schema = TableSchema.builder()
                .column(Column.builder("payload", BasicType.STRING_TYPE)
                        .sourceType("JSON")
                        .build())
                .build();
        CatalogTable table = CatalogTable.builder(path, schema)
                .option(DuckDbCatalog.TABLE_OPTION_DIALECT, DuckDbCatalog.DIALECT)
                .build();

        String ddl = new DuckDbCreateTableSqlBuilder(
                path,
                table,
                new DuckDbTypeMapper())
                .build();

        assertTrue(ddl.contains("\"payload\" JSON"));
    }

    @Test
    public void nestedSourceTypesFallBackToVarchar() {
        TablePath path = TablePath.of("warehouse", "main", "events");
        TableSchema schema = TableSchema.builder()
                .column(Column.builder("items", BasicType.STRING_TYPE)
                        .sourceType("INTEGER[]")
                        .build())
                .build();
        CatalogTable table = CatalogTable.builder(path, schema)
                .option(DuckDbCatalog.TABLE_OPTION_DIALECT, DuckDbCatalog.DIALECT)
                .build();

        String ddl = new DuckDbCreateTableSqlBuilder(
                path,
                table,
                new DuckDbTypeMapper())
                .build();

        assertTrue(ddl.contains("\"items\" VARCHAR"));
        assertFalse(ddl.contains("\"items\" INTEGER[]"));
    }
}
