<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>


    <groupId>com.link.up</groupId>
    <artifactId>link-up</artifactId>
    <version>1.0.0</version>
    <packaging>pom</packaging>

    <name>Link-Up</name>


    <properties>
        <project.build.outputTimestamp>2026-07-24T00:00:00Z</project.build.outputTimestamp>
        <maven-compiler-plugin.version>3.13.0</maven-compiler-plugin.version>
        <maven-assembly-plugin.version>3.3.0</maven-assembly-plugin.version>
        <maven-release-plugin.version>2.5.3</maven-release-plugin.version>
        <maven-javadoc-plugin.version>2.10.3</maven-javadoc-plugin.version>
        <maven-source-plugin.version>2.4</maven-source-plugin.version>
        <maven-surefire-plugin.version>3.0.0-M6</maven-surefire-plugin.version>
        <maven-dependency-plugin.version>3.1.1</maven-dependency-plugin.version>
        <maven-shade-plugin.version>3.2.1</maven-shade-plugin.version>
        <maven.compiler.release>8</maven.compiler.release>
        <junit.version>4.13.2</junit.version>
        <java.version>8</java.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <file_encoding>UTF-8</file_encoding>

        <auto-service.version>1.0.1</auto-service.version>
        <lombok.version>1.18.42</lombok.version>
        <typesafe.version>1.4.3</typesafe.version>
        <log4j2.version>2.23.1</log4j2.version>
        <slf4j.version>2.0.13</slf4j.version>
        <jsqlparser.version>4.9</jsqlparser.version>
        <okhttp.version>4.12.0</okhttp.version>
        <jackson.version>2.15.4</jackson.version>
        <starrocks.thrift.sdk.version>1.0.1</starrocks.thrift.sdk.version>
        <arrow.version>5.0.0</arrow.version>


    </properties>

    <modules>
        <module>link-up-framework</module>
        <module>link-up-launcher</module>
        <module>link-up-bom</module>
        <module>link-up-api</module>
        <module>link-up-connectors</module>
        <module>link-up-dist</module>
        <module>link-up-server</module>
    </modules>


    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <version>${maven-compiler-plugin.version}</version>
                    <configuration>
                        <release>${maven.compiler.release}</release>
                    </configuration>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-surefire-plugin</artifactId>
                    <version>${maven-surefire-plugin.version}</version>
                </plugin>
            </plugins>
        </pluginManagement>
    </build>

</project>
