package com.link.up.connector.jdbc.catalog.postgres;

import com.link.up.api.table.catalog.CatalogTable;
import com.link.up.api.table.catalog.Column;
import com.link.up.api.table.catalog.PrimaryKey;
import com.link.up.api.table.catalog.TablePath;
import com.link.up.api.table.catalog.TableSchema;
import com.link.up.api.table.type.BasicType;
import com.link.up.connector.jdbc.core.dialect.postgres.PostgresTypeMapper;
import org.junit.Test;

import java.util.Arrays;

import static org.junit.Assert.assertTrue;

public class PostgresCreateTableSqlBuilderTest {

    @Test
    public void buildsOfflinePostgresCreateTableSql() {
        Column id =
                Column.builder(
                        "id",
                        BasicType.LONG_TYPE)
                        .nullable(false)
                        .autoIncrement(true)
                        .sourceType(
                                "bigint")
                        .build();

        Column payload =
                Column.builder(
                        "payload",
                        BasicType.STRING_TYPE)
                        .nullable(true)
                        .sourceType(
                                "jsonb")
                        .comment(
                                "raw payload")
                        .build();

        TableSchema schema =
                TableSchema.builder()
                        .columns(
                                Arrays.asList(
                                        id,
                                        payload))
                        .primaryKey(
                                PrimaryKey.of(
                                        "orders_pkey",
                                        Arrays.asList(
                                                "id")))
                        .build();

        CatalogTable table =
                CatalogTable.builder(
                        TablePath.of(
                                "app",
                                "sales",
                                "orders"),
                        schema)
                        .option(
                                PostgresCatalog.TABLE_OPTION_DIALECT,
                                PostgresCatalog.DIALECT)
                        .comment(
                                "orders table")
                        .build();

        String sql =
                new PostgresCreateTableSqlBuilder(
                        table.getTablePath(),
                        table,
                        new PostgresTypeMapper())
                        .build();

        assertTrue(
                sql.contains(
                        "\"id\" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL"));

        assertTrue(
                sql.contains(
                        "\"payload\" jsonb NULL"));

        assertTrue(
                sql.contains(
                        "PRIMARY KEY (\"id\")"));

        assertTrue(
                sql.contains(
                        "COMMENT ON TABLE \"sales\".\"orders\" IS 'orders table';"));

        assertTrue(
                sql.contains(
                        "COMMENT ON COLUMN \"sales\".\"orders\".\"payload\" IS 'raw payload';"));
    }
}
