package com.link.up.connector.jdbc.catalog.oracle;

import com.link.up.api.table.catalog.CatalogTable;
import com.link.up.api.table.catalog.Column;
import com.link.up.api.table.catalog.PrimaryKey;
import com.link.up.api.table.catalog.TablePath;
import com.link.up.api.table.catalog.TableSchema;
import com.link.up.api.table.type.BasicType;
import com.link.up.connector.jdbc.core.dialect.oracle.OracleTypeMapper;
import org.junit.Test;

import java.util.Arrays;
import java.util.List;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertTrue;

public class OracleCreateTableSqlBuilderTest {

    @Test
    public void buildsOfflineCreateTableAndComments() {
        TablePath path =
                TablePath.of(
                        "FREEPDB1",
                        "APP",
                        "users");

        TableSchema schema =
                TableSchema.builder()
                        .column(
                                Column.builder(
                                        "id",
                                        BasicType.LONG_TYPE)
                                        .nullable(false)
                                        .autoIncrement(true)
                                        .build())
                        .column(
                                Column.builder(
                                        "name",
                                        BasicType.STRING_TYPE)
                                        .length(128L)
                                        .nullable(false)
                                        .comment(
                                                "user's name")
                                        .build())
                        .primaryKey(
                                PrimaryKey.of(
                                        "pk_users",
                                        Arrays.asList(
                                                "id")))
                        .build();

        CatalogTable table =
                CatalogTable.builder(
                        path,
                        schema)
                        .comment(
                                "application users")
                        .build();

        List<String> statements =
                new OracleCreateTableSqlBuilder(
                        path,
                        table,
                        new OracleTypeMapper())
                        .buildStatements();

        assertEquals(
                3,
                statements.size());

        String create =
                statements.get(0);

        assertTrue(
                create.contains(
                        "CREATE TABLE \"APP\".\"users\""));

        assertTrue(
                create.contains(
                        "\"id\" NUMBER(19) GENERATED BY DEFAULT AS IDENTITY NOT NULL"));

        assertTrue(
                create.contains(
                        "\"name\" VARCHAR2(128) NOT NULL"));

        assertTrue(
                create.contains(
                        "CONSTRAINT \"pk_users\" PRIMARY KEY (\"id\")"));

        assertEquals(
                "COMMENT ON TABLE \"APP\".\"users\" IS 'application users'",
                statements.get(1));

        assertEquals(
                "COMMENT ON COLUMN \"APP\".\"users\".\"name\" IS 'user''s name'",
                statements.get(2));
    }

    @Test
    public void preservesOracleSourceTypesForOracleToOracleDdl() {
        TablePath path =
                TablePath.of(
                        "FREEPDB1",
                        "APP",
                        "docs");

        TableSchema schema =
                TableSchema.builder()
                        .column(
                                Column.builder(
                                        "payload",
                                        BasicType.STRING_TYPE)
                                        .sourceType(
                                                "CLOB")
                                        .build())
                        .build();

        CatalogTable table =
                CatalogTable.builder(
                        path,
                        schema)
                        .option(
                                OracleCatalog.TABLE_OPTION_DIALECT,
                                OracleCatalog.DIALECT)
                        .build();

        String sql =
                new OracleCreateTableSqlBuilder(
                        path,
                        table,
                        new OracleTypeMapper())
                        .buildStatements()
                        .get(0);

        assertTrue(
                sql.contains(
                        "\"payload\" CLOB"));
    }
}
