package com.link.up.connector.jdbc.catalog.yashandb;

import com.link.up.api.table.catalog.CatalogTable;
import com.link.up.api.table.catalog.Column;
import com.link.up.api.table.catalog.PrimaryKey;
import com.link.up.api.table.catalog.TablePath;
import com.link.up.api.table.catalog.TableSchema;
import com.link.up.api.table.type.BasicType;
import com.link.up.api.table.type.DecimalType;
import com.link.up.connector.jdbc.core.dialect.yashandb.YashanDbTypeMapper;
import org.junit.Test;

import java.util.Arrays;

import static org.junit.Assert.assertTrue;

public class YashanDbCreateTableSqlBuilderTest {

    @Test
    public void buildsIdentityPrimaryKeyAndComments() {
        TablePath path = TablePath.of("YASDB", "APP", "USERS");
        TableSchema schema = TableSchema.builder()
                .column(Column.builder("ID", BasicType.LONG_TYPE)
                        .nullable(false)
                        .autoIncrement(true)
                        .build())
                .column(Column.builder("NAME", BasicType.STRING_TYPE)
                        .length(64L)
                        .comment("display name")
                        .build())
                .column(Column.builder("AMOUNT", new DecimalType(38, 10))
                        .build())
                .primaryKey(PrimaryKey.of("PK_USERS", Arrays.asList("ID")))
                .build();
        CatalogTable table = CatalogTable.builder(path, schema)
                .comment("users table")
                .build();

        String ddl = new YashanDbCreateTableSqlBuilder(
                path,
                table,
                new YashanDbTypeMapper())
                .build();

        assertTrue(ddl.contains("CREATE TABLE \"APP\".\"USERS\""));
        assertTrue(ddl.contains(
                "\"ID\" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL"));
        assertTrue(ddl.contains("\"NAME\" VARCHAR(64 CHAR)"));
        assertTrue(ddl.contains("\"AMOUNT\" NUMBER(38,10)"));
        assertTrue(ddl.contains(
                "CONSTRAINT \"PK_USERS\" PRIMARY KEY (\"ID\")"));
        assertTrue(ddl.contains(
                "COMMENT ON TABLE \"APP\".\"USERS\" IS 'users table'"));
        assertTrue(ddl.contains(
                "COMMENT ON COLUMN \"APP\".\"USERS\".\"NAME\" IS 'display name'"));
    }

    @Test
    public void preservesNativeTypeForSameDialectDdl() {
        TablePath path = TablePath.of("YASDB", "APP", "EVENTS");
        TableSchema schema = TableSchema.builder()
                .column(Column.builder("DOC", BasicType.STRING_TYPE)
                        .sourceType("JSON")
                        .build())
                .build();
        CatalogTable table = CatalogTable.builder(path, schema)
                .option(
                        YashanDbCatalog.TABLE_OPTION_DIALECT,
                        YashanDbCatalog.DIALECT)
                .build();

        String ddl = new YashanDbCreateTableSqlBuilder(
                path,
                table,
                new YashanDbTypeMapper())
                .build();

        assertTrue(ddl.contains("\"DOC\" JSON"));
    }
}
