package com.link.up.connector.jdbc.catalog.hana;

import com.link.up.api.table.catalog.CatalogTable;
import com.link.up.api.table.catalog.Column;
import com.link.up.api.table.catalog.PrimaryKey;
import com.link.up.api.table.catalog.TablePath;
import com.link.up.api.table.catalog.TableSchema;
import com.link.up.api.table.type.BasicType;
import com.link.up.api.table.type.DecimalType;
import com.link.up.connector.jdbc.core.dialect.hana.HanaTypeMapper;
import org.junit.Test;

import java.util.Arrays;

import static org.junit.Assert.assertTrue;

public class HanaCreateTableSqlBuilderTest {

    @Test
    public void buildsHanaCreateColumnTableWithIdentityPrimaryKeyAndComments() {
        TablePath path = TablePath.of("HXE", "SALES", "ORDERS");
        TableSchema schema = TableSchema.builder()
                .column(Column.builder("ID", BasicType.LONG_TYPE)
                        .nullable(false)
                        .autoIncrement(true)
                        .build())
                .column(Column.builder("NAME", BasicType.STRING_TYPE)
                        .length(128L)
                        .build())
                .column(Column.builder("AMOUNT", new DecimalType(20, 4))
                        .precision(20)
                        .scale(4)
                        .comment("order amount")
                        .build())
                .primaryKey(PrimaryKey.of("PK_ORDERS", Arrays.asList("ID")))
                .build();
        CatalogTable table = CatalogTable.builder(path, schema)
                .comment("orders table")
                .build();

        String ddl = new HanaCreateTableSqlBuilder(
                path,
                table,
                new HanaTypeMapper())
                .build();

        assertTrue(ddl.contains("CREATE COLUMN TABLE \"SALES\".\"ORDERS\""));
        assertTrue(ddl.contains(
                "\"ID\" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL"));
        assertTrue(ddl.contains("\"NAME\" NVARCHAR(128)"));
        assertTrue(ddl.contains("\"AMOUNT\" DECIMAL(20,4)"));
        assertTrue(ddl.contains("PRIMARY KEY (\"ID\")"));
        assertTrue(ddl.contains(
                "COMMENT ON TABLE \"SALES\".\"ORDERS\" IS 'orders table'"));
        assertTrue(ddl.contains(
                "COMMENT ON COLUMN \"SALES\".\"ORDERS\".\"AMOUNT\" IS 'order amount'"));
    }

    @Test
    public void preservesNativeHanaTypesForHanaToHanaCopy() {
        TablePath path = TablePath.of("HXE", "SALES", "NATIVE_TYPES");
        TableSchema schema = TableSchema.builder()
                .column(Column.builder("LEVEL", BasicType.SHORT_TYPE)
                        .sourceType("TINYINT")
                        .build())
                .column(Column.builder("EVENT_TIME", BasicType.TIMESTAMP_TYPE)
                        .sourceType("SECONDDATE")
                        .build())
                .build();
        CatalogTable table = CatalogTable.builder(path, schema)
                .option(HanaCatalog.TABLE_OPTION_DIALECT, HanaCatalog.DIALECT)
                .build();

        String ddl = new HanaCreateTableSqlBuilder(
                path,
                table,
                new HanaTypeMapper())
                .build();

        assertTrue(ddl.contains("\"LEVEL\" TINYINT"));
        assertTrue(ddl.contains("\"EVENT_TIME\" SECONDDATE"));
    }
}
