package com.link.up.connector.jdbc.catalog.db2;

import com.link.up.api.table.catalog.CatalogTable;
import com.link.up.api.table.catalog.Column;
import com.link.up.api.table.catalog.PrimaryKey;
import com.link.up.api.table.catalog.TablePath;
import com.link.up.api.table.catalog.TableSchema;
import com.link.up.api.table.type.BasicType;
import com.link.up.api.table.type.DecimalType;
import com.link.up.connector.jdbc.core.dialect.db2.Db2TypeMapper;
import org.junit.Test;

import java.util.Arrays;

import static org.junit.Assert.assertTrue;

public class Db2CreateTableSqlBuilderTest {

    @Test
    public void buildsDb2CreateTableWithIdentityPrimaryKeyAndComments() {
        TablePath path = TablePath.of("SAMPLE", "APP", "USERS");
        TableSchema schema = TableSchema.builder()
                .column(Column.builder("ID", BasicType.LONG_TYPE)
                        .nullable(false)
                        .autoIncrement(true)
                        .build())
                .column(Column.builder("AMOUNT", new DecimalType(31, 10))
                        .precision(31)
                        .scale(10)
                        .comment("order amount")
                        .build())
                .primaryKey(PrimaryKey.of("PK_USERS", Arrays.asList("ID")))
                .build();
        CatalogTable table = CatalogTable.builder(path, schema)
                .comment("users table")
                .build();

        String ddl = new Db2CreateTableSqlBuilder(
                path,
                table,
                new Db2TypeMapper())
                .build();

        assertTrue(ddl.contains("CREATE TABLE \"APP\".\"USERS\""));
        assertTrue(ddl.contains("\"ID\" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL"));
        assertTrue(ddl.contains("\"AMOUNT\" DECIMAL(31,10)"));
        assertTrue(ddl.contains("CONSTRAINT \"PK_USERS\" PRIMARY KEY (\"ID\")"));
        assertTrue(ddl.contains("COMMENT ON TABLE \"APP\".\"USERS\" IS 'users table'"));
        assertTrue(ddl.contains(
                "COMMENT ON COLUMN \"APP\".\"USERS\".\"AMOUNT\" IS 'order amount'"));
    }

    @Test(expected = IllegalArgumentException.class)
    public void autoCreateFailsFastForDecimalPrecisionAboveDb2Limit() {
        TablePath path = TablePath.of("SAMPLE", "APP", "PAYMENTS");
        TableSchema schema = TableSchema.builder()
                .column(Column.builder("AMOUNT", new DecimalType(38, 10))
                        .precision(38)
                        .scale(10)
                        .build())
                .build();
        CatalogTable table = CatalogTable.builder(path, schema).build();

        new Db2CreateTableSqlBuilder(path, table, new Db2TypeMapper()).build();
    }
}
