package com.link.up.connector.jdbc.catalog.opengauss;

import com.link.up.api.table.catalog.CatalogTable;
import com.link.up.api.table.catalog.Column;
import com.link.up.api.table.catalog.PrimaryKey;
import com.link.up.api.table.catalog.TablePath;
import com.link.up.api.table.catalog.TableSchema;
import com.link.up.api.table.type.BasicType;
import com.link.up.api.table.type.DecimalType;
import com.link.up.connector.jdbc.core.dialect.opengauss.OpenGaussTypeMapper;
import org.junit.Test;

import java.util.Arrays;

import static org.junit.Assert.assertTrue;

public class OpenGaussCreateTableSqlBuilderTest {

    @Test
    public void buildsCreateTableWithIdentityPrimaryKeyAndComments() {
        TablePath path = TablePath.of("postgres", "app", "users");
        TableSchema schema = TableSchema.builder()
                .column(Column.builder("id", BasicType.LONG_TYPE)
                        .nullable(false)
                        .autoIncrement(true)
                        .build())
                .column(Column.builder("name", BasicType.STRING_TYPE)
                        .length(64L)
                        .comment("display name")
                        .build())
                .column(Column.builder("amount", new DecimalType(1000, 20))
                        .build())
                .primaryKey(PrimaryKey.of("pk_users", Arrays.asList("id")))
                .build();
        CatalogTable table = CatalogTable.builder(path, schema)
                .comment("users table")
                .build();

        String ddl = new OpenGaussCreateTableSqlBuilder(
                path,
                table,
                new OpenGaussTypeMapper())
                .build();

        assertTrue(ddl.contains("CREATE TABLE \"app\".\"users\""));
        assertTrue(ddl.contains(
                "\"id\" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL"));
        assertTrue(ddl.contains("\"name\" VARCHAR(64 CHAR) NULL"));
        assertTrue(ddl.contains("\"amount\" NUMERIC(1000,20) NULL"));
        assertTrue(ddl.contains("PRIMARY KEY (\"id\")"));
        assertTrue(ddl.contains(
                "COMMENT ON TABLE \"app\".\"users\" IS 'users table'"));
        assertTrue(ddl.contains(
                "COMMENT ON COLUMN \"app\".\"users\".\"name\" IS 'display name'"));
    }

    @Test
    public void preservesNativeTypeForSameDialectDdl() {
        TablePath path = TablePath.of("postgres", "app", "events");
        TableSchema schema = TableSchema.builder()
                .column(Column.builder("payload", BasicType.STRING_TYPE)
                        .sourceType("JSONB")
                        .build())
                .build();
        CatalogTable table = CatalogTable.builder(path, schema)
                .option(
                        OpenGaussCatalog.TABLE_OPTION_DIALECT,
                        OpenGaussCatalog.DIALECT)
                .build();

        String ddl = new OpenGaussCreateTableSqlBuilder(
                path,
                table,
                new OpenGaussTypeMapper())
                .build();

        assertTrue(ddl.contains("\"payload\" JSONB NULL"));
    }
}
