package com.link.up.connector.jdbc.catalog.postgres;

import com.link.up.api.table.catalog.CatalogTable;
import com.link.up.api.table.catalog.Column;
import com.link.up.api.table.catalog.PrimaryKey;
import com.link.up.api.table.catalog.TablePath;
import com.link.up.api.table.catalog.TableSchema;
import com.link.up.api.table.type.SqlType;
import com.link.up.connector.jdbc.core.dialect.postgres.PostgresTypeMapper;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Locale;
import java.util.regex.Pattern;
import java.util.stream.Collectors;

/**
 * PostgreSQL CREATE TABLE SQL 构造器。
 *
 * <p>离线适配第一阶段只生成字段、NULL/NOT NULL、默认值、Identity、
 * 主键和注释，不引入 tablespace、fillfactor、外键或实时 Schema Event。
 */
public final class PostgresCreateTableSqlBuilder {

    private static final Pattern NUMBER_PATTERN =
            Pattern.compile(
                    "[-+]?\\d+(\\.\\d+)?");

    private final TablePath tablePath;
    private final CatalogTable catalogTable;
    private final PostgresTypeMapper typeMapper;

    public PostgresCreateTableSqlBuilder(
            TablePath tablePath,
            CatalogTable catalogTable,
            PostgresTypeMapper typeMapper) {

        this.tablePath = tablePath;
        this.catalogTable = catalogTable;
        this.typeMapper = typeMapper;
    }

    public String build() {
        return String.join(
                "\n",
                buildStatements());
    }

    public List<String> buildStatements() {
        List<String> statements =
                new ArrayList<String>();

        statements.add(
                buildCreateTable());

        if (hasText(
                catalogTable.getComment())) {

            statements.add(
                    "COMMENT ON TABLE "
                            + quoteTable(tablePath)
                            + " IS '"
                            + escapeLiteral(
                            catalogTable.getComment())
                            + "';");
        }

        for (Column column :
                catalogTable.getTableSchema()
                        .getColumns()) {

            if (hasText(column.getComment())) {
                statements.add(
                        "COMMENT ON COLUMN "
                                + quoteTable(tablePath)
                                + "."
                                + quoteIdentifier(
                                column.getName())
                                + " IS '"
                                + escapeLiteral(
                                column.getComment())
                                + "';");
            }
        }

        return Collections.unmodifiableList(
                statements);
    }

    /**
     * Builds one column definition for offline ADD COLUMN preparation.
     */
    public String buildColumnDefinition(
            Column column,
            boolean preserveSourceType) {

        List<String> parts =
                new ArrayList<String>();

        parts.add(
                quoteIdentifier(
                        column.getName()));

        parts.add(
                typeMapper.toDatabaseType(
                        column,
                        preserveSourceType));

        if (column.isAutoIncrement()
                && isInteger(
                column.getDataType()
                        .getSqlType())) {

            parts.add(
                    "GENERATED BY DEFAULT AS IDENTITY");
        }

        parts.add(
                column.isNullable()
                        ? "NULL"
                        : "NOT NULL");

        if (!column.isAutoIncrement()
                && column.getDefaultValue() != null) {

            parts.add(
                    "DEFAULT "
                            + formatDefaultValue(
                            column,
                            preserveSourceType));
        }

        return String.join(
                " ",
                parts);
    }

    private String buildCreateTable() {
        TableSchema schema =
                catalogTable.getTableSchema();

        List<String> definitions =
                new ArrayList<String>();

        boolean preserveSourceType =
                PostgresCatalog.DIALECT
                        .equalsIgnoreCase(
                                catalogTable.getOptions()
                                        .get(
                                                PostgresCatalog
                                                        .TABLE_OPTION_DIALECT));

        for (Column column :
                schema.getColumns()) {

            definitions.add(
                    buildColumnDefinition(
                            column,
                            preserveSourceType));
        }

        PrimaryKey primaryKey =
                schema.getPrimaryKey();

        if (primaryKey != null) {
            definitions.add(
                    buildPrimaryKey(
                            primaryKey));
        }

        return "CREATE TABLE "
                + quoteTable(tablePath)
                + " (\n    "
                + String.join(
                ",\n    ",
                definitions)
                + "\n);";
    }

    private String buildPrimaryKey(
            PrimaryKey primaryKey) {

        String columns =
                primaryKey.getColumnNames()
                        .stream()
                        .map(
                                PostgresCreateTableSqlBuilder
                                        ::quoteIdentifier)
                        .collect(
                                Collectors.joining(", "));

        return "PRIMARY KEY ("
                + columns
                + ")";
    }

    private String formatDefaultValue(
            Column column,
            boolean preserveSourceType) {

        Object value =
                column.getDefaultValue();

        if (value instanceof Number) {
            return value.toString();
        }

        if (value instanceof Boolean) {
            return (Boolean) value
                    ? "TRUE"
                    : "FALSE";
        }

        String text =
                String.valueOf(value)
                        .trim();

        if (preserveSourceType) {
            return text;
        }

        String upper =
                text.toUpperCase(
                        Locale.ROOT);

        if ("NULL".equals(upper)
                || "CURRENT_TIMESTAMP".equals(upper)
                || upper.startsWith(
                "CURRENT_TIMESTAMP(")
                || "CURRENT_DATE".equals(upper)
                || "CURRENT_TIME".equals(upper)
                || "NOW()".equals(upper)) {

            return text;
        }

        SqlType sqlType =
                column.getDataType()
                        .getSqlType();

        if (isNumeric(sqlType)
                && NUMBER_PATTERN
                .matcher(text)
                .matches()) {

            return text;
        }

        return "'"
                + escapeLiteral(text)
                + "'";
    }

    private static boolean isInteger(
            SqlType sqlType) {

        return sqlType == SqlType.TINYINT
                || sqlType == SqlType.SMALLINT
                || sqlType == SqlType.INT
                || sqlType == SqlType.BIGINT;
    }

    private static boolean isNumeric(
            SqlType sqlType) {

        return isInteger(sqlType)
                || sqlType == SqlType.FLOAT
                || sqlType == SqlType.DOUBLE
                || sqlType == SqlType.DECIMAL;
    }

    private static String quoteTable(
            TablePath tablePath) {

        if (!hasText(
                tablePath.getSchemaName())) {

            throw new IllegalArgumentException(
                    "PostgreSQL tablePath must contain schema: "
                            + tablePath);
        }

        return quoteIdentifier(
                tablePath.getSchemaName())
                + "."
                + quoteIdentifier(
                tablePath.getTableName());
    }

    private static String quoteIdentifier(
            String value) {

        if (!hasText(value)) {
            throw new IllegalArgumentException(
                    "identifier must not be empty");
        }

        return "\""
                + value.trim()
                .replace("\"", "\"\"")
                + "\"";
    }

    private static String escapeLiteral(
            String value) {

        return value.replace(
                "'",
                "''");
    }

    private static boolean hasText(
            String value) {

        return value != null
                && !value.trim()
                .isEmpty();
    }
}
