package com.link.up.connector.jdbc.catalog.db2;

import com.link.up.api.table.catalog.CatalogTable;
import com.link.up.api.table.catalog.Column;
import com.link.up.api.table.catalog.PrimaryKey;
import com.link.up.api.table.catalog.TablePath;
import com.link.up.api.table.catalog.TableSchema;
import com.link.up.api.table.type.SqlType;
import com.link.up.connector.jdbc.core.dialect.db2.Db2TypeMapper;

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Locale;
import java.util.Set;
import java.util.regex.Pattern;
import java.util.stream.Collectors;

/** DB2 offline CREATE TABLE builder. */
public final class Db2CreateTableSqlBuilder {

    private static final Pattern NUMBER_PATTERN =
            Pattern.compile("[-+]?\\d+(\\.\\d+)?");

    private final TablePath tablePath;
    private final CatalogTable catalogTable;
    private final Db2TypeMapper typeMapper;

    public Db2CreateTableSqlBuilder(
            TablePath tablePath,
            CatalogTable catalogTable,
            Db2TypeMapper typeMapper) {
        this.tablePath = tablePath;
        this.catalogTable = catalogTable;
        this.typeMapper = typeMapper;
    }

    public String build() {
        return buildStatements().stream()
                .map(sql -> sql.endsWith(";") ? sql : sql + ";")
                .collect(Collectors.joining("\n"));
    }

    public List<String> buildStatements() {
        TableSchema schema = catalogTable.getTableSchema();
        PrimaryKey primaryKey = schema.getPrimaryKey();
        Set<String> primaryKeyColumns = primaryKey == null
                ? new HashSet<String>()
                : new HashSet<String>(primaryKey.getColumnNames());

        boolean preserveSourceType = Db2Catalog.DIALECT.equalsIgnoreCase(
                catalogTable.getOptions().get(Db2Catalog.TABLE_OPTION_DIALECT));

        List<String> definitions = new ArrayList<String>();
        for (Column column : schema.getColumns()) {
            definitions.add(buildColumnDefinition(
                    column,
                    preserveSourceType,
                    primaryKeyColumns.contains(column.getName())));
        }
        if (primaryKey != null) {
            definitions.add(buildPrimaryKey(primaryKey));
        }

        List<String> statements = new ArrayList<String>();
        statements.add(
                "CREATE TABLE " + quoteTable(tablePath)
                        + " (\n    "
                        + String.join(",\n    ", definitions)
                        + "\n)");

        if (hasText(catalogTable.getComment())) {
            statements.add(
                    "COMMENT ON TABLE " + quoteTable(tablePath)
                            + " IS '" + escapeLiteral(catalogTable.getComment()) + "'");
        }
        for (Column column : schema.getColumns()) {
            if (hasText(column.getComment())) {
                statements.add(
                        "COMMENT ON COLUMN " + quoteTable(tablePath) + "."
                                + quoteIdentifier(column.getName())
                                + " IS '" + escapeLiteral(column.getComment()) + "'");
            }
        }
        return statements;
    }

    public String buildColumnDefinition(Column column, boolean preserveSourceType) {
        return buildColumnDefinition(column, preserveSourceType, false);
    }

    private String buildColumnDefinition(
            Column column,
            boolean preserveSourceType,
            boolean primaryKeyColumn) {

        List<String> parts = new ArrayList<String>();
        parts.add(quoteIdentifier(column.getName()));
        parts.add(typeMapper.toDatabaseType(column, preserveSourceType));

        if (column.isAutoIncrement()) {
            parts.add("GENERATED BY DEFAULT AS IDENTITY");
        } else if (column.getDefaultValue() != null) {
            parts.add("DEFAULT " + formatDefaultValue(column, preserveSourceType));
        }

        if (!column.isNullable() || primaryKeyColumn) {
            parts.add("NOT NULL");
        }
        return String.join(" ", parts);
    }

    private String buildPrimaryKey(PrimaryKey primaryKey) {
        String columns = primaryKey.getColumnNames().stream()
                .map(Db2CreateTableSqlBuilder::quoteIdentifier)
                .collect(Collectors.joining(", "));
        String name = primaryKey.getName();
        if (!hasText(name)) {
            return "PRIMARY KEY (" + columns + ")";
        }
        return "CONSTRAINT " + quoteIdentifier(name)
                + " PRIMARY KEY (" + columns + ")";
    }

    private String formatDefaultValue(Column column, boolean preserveSourceType) {
        Object value = column.getDefaultValue();
        if (preserveSourceType) {
            String expression = String.valueOf(value).trim();
            if (hasText(expression)) {
                return expression;
            }
        }
        if (value instanceof Number) {
            return value.toString();
        }
        if (value instanceof Boolean) {
            return (Boolean) value ? "TRUE" : "FALSE";
        }

        String text = String.valueOf(value).trim();
        String upper = text.toUpperCase(Locale.ROOT);
        if ("NULL".equals(upper)
                || upper.startsWith("CURRENT ")
                || upper.startsWith("CURRENT_")
                || "USER".equals(upper)
                || "SESSION_USER".equals(upper)
                || "SYSTEM_USER".equals(upper)) {
            return text;
        }

        SqlType sqlType = column.getDataType().getSqlType();
        if (isNumeric(sqlType) && NUMBER_PATTERN.matcher(text).matches()) {
            return text;
        }
        return "'" + escapeLiteral(text) + "'";
    }

    private static boolean isNumeric(SqlType type) {
        return type == SqlType.TINYINT
                || type == SqlType.SMALLINT
                || type == SqlType.INT
                || type == SqlType.BIGINT
                || type == SqlType.FLOAT
                || type == SqlType.DOUBLE
                || type == SqlType.DECIMAL;
    }

    private static String quoteTable(TablePath tablePath) {
        if (!hasText(tablePath.getSchemaName())) {
            throw new IllegalArgumentException(
                    "DB2 CREATE TABLE 需要 schema：" + tablePath);
        }
        return quoteIdentifier(tablePath.getSchemaName())
                + "."
                + quoteIdentifier(tablePath.getTableName());
    }

    private static String quoteIdentifier(String value) {
        if (!hasText(value)) {
            throw new IllegalArgumentException("identifier must not be empty");
        }
        return "\"" + value.trim().replace("\"", "\"\"") + "\"";
    }

    private static String escapeLiteral(String value) {
        return value.replace("'", "''");
    }

    private static boolean hasText(String value) {
        return value != null && !value.trim().isEmpty();
    }
}
